services:
  daily-trends-api:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: development
    container_name: daily-trends-api
    image: daily-trends-api:1.0.0
    ports:
      - '5000:5000'
    environment:
      MONGO_HOST: mongo
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
